set_property PACKAGE_PIN K17 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CS]
set_property PACKAGE_PIN V15 [get_ports {SEGMENTS[6]}]
set_property PACKAGE_PIN V8 [get_ports CS]
set_property PACKAGE_PIN W8 [get_ports MOSI]
set_property PACKAGE_PIN U7 [get_ports MISO]
set_property PACKAGE_PIN V7 [get_ports SCLK]
set_property PACKAGE_PIN T16 [get_ports {OPERATION[0]}]
set_property PACKAGE_PIN W13 [get_ports {OPERATION[1]}]
set_property PACKAGE_PIN P15 [get_ports {OPERATION[2]}]
set_property PACKAGE_PIN G15 [get_ports {OPERATION[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports DIGIT_SELECT]
set_property IOSTANDARD LVCMOS33 [get_ports MISO]
set_property IOSTANDARD LVCMOS33 [get_ports MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports {OPERATION[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OPERATION[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OPERATION[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OPERATION[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENTS[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENTS[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENTS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENTS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENTS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENTS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENTS[6]}]

create_clock -period 8.000 -name CLK -waveform {0.000 4.000} [get_ports CLK]



set_property PACKAGE_PIN K18 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]

set_property PACKAGE_PIN W15 [get_ports {SEGMENTS[5]}]
set_property PACKAGE_PIN T11 [get_ports {SEGMENTS[4]}]
set_property PACKAGE_PIN T10 [get_ports {SEGMENTS[3]}]
set_property PACKAGE_PIN T14 [get_ports {SEGMENTS[2]}]
set_property PACKAGE_PIN T15 [get_ports {SEGMENTS[1]}]
set_property PACKAGE_PIN P14 [get_ports {SEGMENTS[0]}]
set_property PACKAGE_PIN R14 [get_ports DIGIT_SELECT]

set_property IOSTANDARD LVCMOS33 [get_ports DONE_SETUP]
set_property PACKAGE_PIN M14 [get_ports DONE_SETUP]
